### ISSUE TITLE
如果能生成视频那价值会大大提升。。

### ISSUE THREAD

**Issue by MAYBreath** [changbowen/Ken-Burns-Slideshow#11]
其实已经有个老外用一键工具ffmpeg 生成了。。
https://el-tramo.be/blog/ken-burns-ffmpeg/
只是这个老外生成的视频会地震 不知道为啥。。

**Comment by changbowen** [comment]
恩，可惜我不会……
我之前曲线救国用Geforce Experience录屏效果还行，不怎么影响播放效果。
A卡的话有ReLive

**Comment by MAYBreath** [comment]
经过2天的艰苦攻坚！我会了！而且不会地震了。。就用ffmpeg就可以搞定了 用C#重写了一下 一键生成视频，感觉还不错

**Comment by changbowen** [comment]
57214b36583793604d8812bd67b4e98421846f80
added to readme
