### ISSUE TITLE
发现一个关于图片方向的奇怪bug。

### ISSUE THREAD

**Issue by sutking** [changbowen/Ken-Burns-Slideshow#2]
用windows自带的图片查看器打开的图片显示的方向是正确的，但是KBS（是否可以这样简称你的作品？）播放的时候图片的方向就被随机旋转了（顺、逆时针90°，或是直接180°），之所以说随机是因为目前我还没有找到这其中的规律，有的图片会出现有的不会；而且出现bug的图片被旋转的方向都不同，不过如果出现bug的图片下次在播放的时候还是同样错误的方向不变，试过右键单击图片选择“向右旋转”或者“向左旋转”都无济于事，希望修补这个奇怪的bug，谢谢！

**Comment by changbowen** [comment]
请参考[这篇文章](http://www.howtogeek.com/254830/why-your-photos-dont-always-appear-correctly-rotated/)。
有些图片的EXIF信息中储存了旋转方向，而目前此程序并不包含处理EXIF信息的功能，所有图片按照原始像素显示。如果查看器在旋转图片时仅将方向存储到了EXIF而没有修改实际像素，此程序显示的图片方向会和查看器不一致。
我会尝试加入读取和处理EXIF信息以解决此类问题。

**Comment by changbowen** [comment]
@sutking 试一下最新的release看还有没有旋转不正常的情况。

**Comment by sutking** [comment]
经测试，bug已修复，幸苦！

**Comment by sutking** [comment]
又发现一个程序崩溃的bug，不知道是该new issue呢还是可以直接加在这个下边？

**Comment by changbowen** [comment]
@sutking 什么情况下崩溃？

**Comment by sutking** [comment]
![1](https://cloud.githubusercontent.com/assets/16184781/17807151/6add970a-663b-11e6-8443-da35f8a062f0.JPG)
windows 10 64位，软件对于cpu和ram的用量大概如图，经多次测试，都是播放10分钟左右便弹出
![default](https://cloud.githubusercontent.com/assets/16184781/17807202/b5315710-663b-11e6-9a6a-be73e0420dde.JPG)
这样的ben'kui崩溃信息，不知是我电脑硬件不太给力？

**Comment by changbowen** [comment]
不是很好找原因，我测试的时候没发现崩溃的现象。
图片很大吗？还是你是选择的一次性载入？一般720p左右的图片4GB内存占用大概在100MB左右
方便把程序根目录的config.xml、config_instant.xml（如果有）发过来吗？
最好用到的图片和音乐也能发给我以便确定问题。

**Comment by changbowen** [comment]
@sutking 不是很好找原因，我测试的时候没发现崩溃的现象。
图片很大吗？还是你是选择的一次性载入？一般720p左右的图片4GB内存占用大概在100MB左右
方便把程序根目录的config.xml、config_instant.xml（如果有）发过来吗？
最好用到的图片和音乐也能发给我以便确定问题。

**Comment by sutking** [comment]
平均每张照片2Mb左右，没有BGM，没有config_instant.xml
[config.zip](https://github.com/changbowen/Ken-Burns-Slideshow/files/427274/config.zip)
![default](https://cloud.githubusercontent.com/assets/16184781/17814127/e54fe7ca-6660-11e6-8e28-3d681e1c7105.jpg)
这个是设置截图

**Comment by changbowen** [comment]
@sutking 没发现什么异常。是不是在显示某张图片时报错？但图片加载失败时有try catch，应该是不会崩溃的。
我这边相同配置，4MB的图片内存占用也只有150MB左右。
用其他图片播放试一下看有没有问题。

**Comment by sutking** [comment]
嗯，大概是我的图片的原因了，换了别的图片再测试就没有问题了
